[phases.setup]
nixPkgs = ["nodejs", "python3", "python3-pip"]

[phases.install]
# Use corepack to manage pnpm and standard pip for Python
cmds = [
    "npm install -g corepack",
    "corepack enable",
    "corepack prepare pnpm@10.6.3 --activate",
    "cd /app/frontend && pnpm install",
    "cd /app && python3 -m pip install -r requirements.txt",
]

[phases.build]
cmds = [
    "cd /app/frontend && pnpm build",
    "cd /app && python3 manage.py collectstatic --noinput",
]

[start]
cmd = "gunicorn gimli.wsgi:application --bind 0.0.0.0:$PORT"
