[phases.setup]
nixPkgs = ["nodejs", "python3", "curl"]

[phases.install]
# Use corepack to manage pnpm and install uv directly
cmds = [
    "npm install -g corepack",
    "corepack enable",
    "corepack prepare pnpm@10.6.3 --activate",
    "cd /app/frontend && pnpm install",
    "curl -LsSf https://astral.sh/uv/install.sh | sh",
    "export PATH=\"$HOME/.local/bin:$PATH\"",
    "cd /app && $HOME/.local/bin/uv pip install -r requirements.txt",
]

[phases.build]
cmds = [
    "cd /app/frontend && pnpm build",
    "cd /app && python3 manage.py collectstatic --noinput",
]

[start]
cmd = "gunicorn gimli.wsgi:application --bind 0.0.0.0:$PORT"
