[phases.setup]
nixPkgs = ["nodejs", "python3"]

[phases.install]
# Use corepack to reliably install and manage pnpm
cmds = [
    "npm install -g corepack",
    "corepack enable",
    "corepack prepare pnpm@10.6.3 --activate",
    "cd frontend && pnpm install",
    "cd .. && pip install -r requirements.txt",
]

[phases.build]
cmds = [
    "cd frontend && pnpm build",
    "cd .. && python manage.py collectstatic --noinput",
]

[start]
cmd = "gunicorn gimli.wsgi:application --bind 0.0.0.0:$PORT"
