# Generated by Django 5.0.2 on 2025-03-16 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('character_class', models.CharField(choices=[('barbarian', 'Barbarian'), ('bard', 'Bard'), ('cleric', 'Cleric'), ('druid', 'Druid'), ('fighter', 'Fighter'), ('monk', 'Monk'), ('paladin', 'Paladin'), ('ranger', 'Ranger'), ('rogue', 'Rogue'), ('sorcerer', 'Sorcerer'), ('warlock', 'Warlock'), ('wizard', 'Wizard'), ('artificer', 'Artificer'), ('blood_hunter', 'Blood Hunter')], default='fighter', max_length=20)),
                ('race', models.CharField(choices=[('dragonborn', 'Dragonborn'), ('dwarf', 'Dwarf'), ('elf', 'Elf'), ('gnome', 'Gnome'), ('half_elf', 'Half-Elf'), ('half_orc', 'Half-Orc'), ('halfling', 'Halfling'), ('human', 'Human'), ('tiefling', 'Tiefling'), ('orc', 'Orc'), ('leonin', 'Leonin'), ('satyr', 'Satyr'), ('aasimar', 'Aasimar'), ('fairy', 'Fairy'), ('harengon', 'Harengon'), ('tabaxi', 'Tabaxi'), ('tortle', 'Tortle'), ('genasi', 'Genasi'), ('goliath', 'Goliath'), ('other', 'Other')], default='human', max_length=20)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('alignment', models.CharField(choices=[('lg', 'Lawful Good'), ('ng', 'Neutral Good'), ('cg', 'Chaotic Good'), ('ln', 'Lawful Neutral'), ('nn', 'True Neutral'), ('cn', 'Chaotic Neutral'), ('le', 'Lawful Evil'), ('ne', 'Neutral Evil'), ('ce', 'Chaotic Evil')], default='nn', max_length=2)),
                ('bio', models.TextField(blank=True)),
                ('character_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='lore.campaign')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
